name: time-series-forecasting

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - python-binance==1.0.19
    - pandas==2.2
    - scikit-learn==1.4
    - plotly==5.20
    - jupyter==1.0
    - pyarrow==15.0 # for parquet
